// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "ch.qos.logback" % "logback-classic" % "1.2.3",
      "ch.qos.logback" % "logback-core" % "1.2.3",
      "com.chuusai" % "shapeless_2.12" % "2.3.3",
      "com.fasterxml.jackson.core" % "jackson-annotations" % "2.9.8",
      "com.fasterxml.jackson.core" % "jackson-core" % "2.9.8",
      "com.fasterxml.jackson.core" % "jackson-databind" % "2.9.8",
      "com.fasterxml.jackson.datatype" % "jackson-datatype-jdk8" % "2.9.8",
      "com.fasterxml.jackson.datatype" % "jackson-datatype-jsr310" % "2.9.8",
      "com.typesafe" % "config" % "1.3.4",
      "com.typesafe" % "ssl-config-core_2.12" % "0.3.7",
      "com.typesafe.akka" % "akka-actor_2.12" % "2.5.22",
      "com.typesafe.akka" % "akka-http-core_2.12" % "10.1.8",
      "com.typesafe.akka" % "akka-http_2.12" % "10.1.8",
      "com.typesafe.akka" % "akka-parsing_2.12" % "10.1.8",
      "com.typesafe.akka" % "akka-protobuf_2.12" % "2.5.22",
      "com.typesafe.akka" % "akka-stream_2.12" % "2.5.22",
      "com.typesafe.play" % "play-functional_2.12" % "2.7.3",
      "com.typesafe.play" % "play-json_2.12" % "2.7.3",
      "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.9.2",
      "de.heikoseeberger" % "akka-http-play-json_2.12" % "1.25.2",
      "eu.timepit" % "refined_2.12" % "0.9.5",
      "joda-time" % "joda-time" % "2.10.1",
      "org.julienrf" % "play-json-derived-codecs_2.12" % "5.0.0",
      "org.reactivestreams" % "reactive-streams" % "1.0.2",
      "org.scala-lang.modules" % "scala-java8-compat_2.12" % "0.8.0",
      "org.scala-lang.modules" % "scala-parser-combinators_2.12" % "1.1.1",
      "org.scala-lang.modules" % "scala-xml_2.12" % "1.2.0",
      "org.slf4j" % "slf4j-api" % "1.7.25",
      "org.typelevel" % "macro-compat_2.12" % "1.1.1"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH 0046bfbd5c568611ecfa96956aca841ee6df9294