// DON'T EDIT THIS FILE.
// This file is auto generated by sbt-lock 0.6.0.
// https://github.com/tkawachi/sbt-lock/
dependencyOverrides ++= {
  if (!(sbtLockHashIsUpToDate in ThisBuild).value && sbtLockIgnoreOverridesOnStaleHash.value) {
    Seq.empty
  } else {
    Seq(
      "ch.qos.logback" % "logback-classic" % "1.2.3",
      "ch.qos.logback" % "logback-core" % "1.2.3",
      "com.typesafe.scala-logging" % "scala-logging_2.12" % "3.9.2",
      "org.slf4j" % "slf4j-api" % "1.7.25"
    )
  }
}
// LIBRARY_DEPENDENCIES_HASH 51ccd8116183aace05288048b66193c1d48074e0