addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage" % "sbt-scoverage" % "1.5.1")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.0.0")
addSbtPlugin("org.wartremover" % "sbt-wartremover" % "2.4.1")
addSbtPlugin("com.github.tkawachi" % "sbt-lock" % "0.6.0")
