openapi: 3.0.1

info:
  title: Money Transfer API
  description: |-
    API for money transfers between accounts which may be invoked by multiple
    systems and services on behalf of end users.
  version: 1.0.0

servers:
  - url: 'https://{host}:{port}'
    variables:
      host:
        default: localhost
      port:
        default: 443
  - url: 'http://{host}:{port}'
    variables:
      host:
        default: localhost
      port:
        default: 80

paths:

  /accounts:

    post:
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /accounts/{id}:
    parameters:
      - in: path
        name: id
        schema:
          $ref: '#/components/schemas/AccountId'
        required: true
        description: The account id

    get:
      summary: Get an account by its id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: An account with the given id was not found

  /transfers:

    post:
      summary: Create a money transfer request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferId'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    get:
      summary: Get all transfers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

  /transfers?accountId={accId}:
    parameters:
      - in: query
        name: accId
        schema:
          $ref: '#/components/schemas/AccountId'
        required: true
        description: The account id

    get:
      summary: Get transfers by account ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: A transfer with the given id was not found

  /transfers/{id}:
    parameters:
      - in: path
        name: id
        schema:
          $ref: '#/components/schemas/TransferId'
        required: true
        description: The transfer id

    get:
      summary: Get a transfer by its id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: A transfer with the given id was not found

components:
  schemas:

    AccountRequest:
      properties:
        requestId:
          $ref: '#/components/schemas/RequestId'
        balance:
          $ref: '#/components/schemas/Money'
      required:
        - requestId
        - systemId
        - balance

    RequestId:
      type: string
      format: uuid

    Error:
      type: string

    Account:
      properties:
        id:
          $ref: '#/components/schemas/AccountId'
        balance:
          $ref: '#/components/schemas/Money'
      required:
        - id
        - balance

    AccountId:
      type: integer

    Money:
      type: integer
      description: non-negative amount in cents

    TransferRequest:
      properties:
        requestId:
          $ref: '#/components/schemas/RequestId'
        sender:
          $ref: '#/components/schemas/AccountId'
        receiver:
          $ref: '#/components/schemas/AccountId'
        amount:
          $ref: '#/components/schemas/Money'
      required:
        - requestId
        - systemId
        - sender
        - receiver
        - amount

    Transfer:
      properties:
        id:
          $ref: '#/components/schemas/TransferId'
        sender:
          $ref: '#/components/schemas/AccountId'
        receiver:
          $ref: '#/components/schemas/AccountId'
        amount:
          $ref: '#/components/schemas/Money'
        status:
          $ref: '#/components/schemas/TransferStatus'
        reasonOfDecline:
          type: string
      required:
        - id
        - sender
        - receiver
        - amount
        - status

    TransferId:
      type: integer

    TransferStatus:
      type: string
      enum: [completed, declined]
