openapi: 3.0.1

info:
  title: Money Transfer API
  description: |-
    API for money transfers between accounts which may be invoked by multiple
    systems and services on behalf of end users.
  version: 1.0.0

servers:
  - url: 'http://{host}:{port}'
    variables:
      host:
        default: localhost
      port:
        default: 8080

paths:

  /accounts:

    post:
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'

    get:
      summary: Get all accounts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'

  /transfers:

    post:
      summary: Create a money transfer request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transfer'

    get:
      summary: Get all money transfers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Transfer'

components:
  schemas:

    AccountRequest:
      properties:
        balance:
          $ref: '#/components/schemas/AmountInCents'
      required:
        - requestId
        - systemId
        - balance

    Account:
      properties:
        id:
          $ref: '#/components/schemas/AccountId'
        balance:
          $ref: '#/components/schemas/AmountInCents'
      required:
        - id
        - balance

    AccountId:
      type: integer

    AmountInCents:
      type: integer
      description: non-negative amount in cents

    TransferRequest:
      properties:
        from:
          $ref: '#/components/schemas/AccountId'
        to:
          $ref: '#/components/schemas/AccountId'
        amount:
          $ref: '#/components/schemas/AmountInCents'
      required:
        - from
        - to
        - amount

    Transfer:
      properties:
        id:
          $ref: '#/components/schemas/TransferId'
        from:
          $ref: '#/components/schemas/AccountId'
        to:
          $ref: '#/components/schemas/AccountId'
        amount:
          $ref: '#/components/schemas/AmountInCents'
        status:
          $ref: '#/components/schemas/TransferStatus'
      required:
        - id
        - from
        - to
        - amount
        - status

    TransferId:
      type: integer

    TransferStatus:
      type: string
      enum: [Completed, InsufficientFunds]
